name: FastAPI-Pipeline

on:
  push:
    branches:
    - main
    - source_code
    - four_lecture_gab
  pull_request:
    branches:
    - main

jobs:
  ct_pipeline:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Training model
          run: |
            python python train.py
#            --tracking_uri ${{ secrets.TRACKING_URI}} --tracking_username ${{ secrets.TRACKING_USERNAME}} --tracking_password ${{ secrets.TRACKING_PASSWORD}} --registry_model_name ${{ secrets.REGISTRY_MODEL_NAME}}
